# Generated by Django 5.0.4 on 2025-08-04 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0020_alter_ndrcorecolorscheme_accent_color_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='field_size',
        ),
        migrations.AddField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='field_column_span',
            field=models.IntegerField(default=1, help_text='Number of columns to span', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='field_row_span',
            field=models.IntegerField(default=1, help_text='Number of rows to span', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='field_row',
            field=models.IntegerField(help_text='The row in the card. Starts with 1.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
