# Generated by Django 5.0.4 on 2025-10-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0021_remove_ndrcoreresultfieldcardconfiguration_field_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='h1_size',
            field=models.CharField(default='2rem', max_length=10),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='h2_size',
            field=models.CharField(default='1.75rem', max_length=10),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='h3_size',
            field=models.CharField(default='1.5rem', max_length=10),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='h4_size',
            field=models.CharField(default='1.25rem', max_length=10),
        ),
        migrations.AlterField(
            model_name='ndrcorepage',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Template Page'), (3, 'Search Page'), (4, 'Data List Page'), (5, 'Contact Form'), (7, 'Flip Book'), (8, 'About Us Page')], default=1, help_text='Choose a type for your page.'),
        ),
    ]
