# Generated by Django 5.0.4 on 2025-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0022_ndrcorecolorscheme_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='border_label',
            field=models.CharField(blank=True, default='', help_text='Label text to display on the top border of the field box', max_length=100),
        ),
    ]
