# Generated by Django 5.0.4 on 2025-10-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0023_ndrcoreresultfieldcardconfiguration_border_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='border_label',
        ),
        migrations.AddField(
            model_name='ndrcoreresultfield',
            name='border_label',
            field=models.CharField(blank=True, default='', help_text='Label text to display on the top border of the field box', max_length=100),
        ),
    ]
