# Generated by Django 5.0.4 on 2025-10-19 16:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0024_remove_ndrcoreresultfieldcardconfiguration_border_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='brand_panel_bg',
            field=colorfield.fields.ColorField(default='#00b0b9', help_text='Background color of the brand panel.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='brand_panel_text',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Text color of the brand panel.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_accent_color_1',
            field=colorfield.fields.ColorField(default='#0d6efd', help_text='Accent color 1 for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_accent_color_2',
            field=colorfield.fields.ColorField(default='#6ea8fe', help_text='Accent color 2 for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_background_color',
            field=colorfield.fields.ColorField(default='#121212', help_text='Background color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_brand_panel_bg',
            field=colorfield.fields.ColorField(default='#008a92', help_text='Brand panel background color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_brand_panel_text',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Brand panel text color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_button_border_color',
            field=colorfield.fields.ColorField(default='#0d6efd', help_text='Primary button border color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_button_color',
            field=colorfield.fields.ColorField(default='#0d6efd', help_text='Primary button background color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_button_hover_color',
            field=colorfield.fields.ColorField(default='#0b5ed7', help_text='Primary button hover color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Primary button text color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_container_bg_color',
            field=colorfield.fields.ColorField(default='#1e1e1e', help_text='Container background color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_error_color',
            field=colorfield.fields.ColorField(default='#dc3545', help_text='Error alert color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_footer_bg',
            field=colorfield.fields.ColorField(default='#212529', help_text='Footer background color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_footer_link_color',
            field=colorfield.fields.ColorField(default='#adb5bd', help_text='Footer link color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_footer_link_hover_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Footer link hover color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_form_field_bg',
            field=colorfield.fields.ColorField(default='#2a2a2a', help_text='Form field background color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_form_field_fg',
            field=colorfield.fields.ColorField(default='#e9ecef', help_text='Form field text color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_info_color',
            field=colorfield.fields.ColorField(default='#0dcaf0', help_text='Info alert color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_link_color',
            field=colorfield.fields.ColorField(default='#6ea8fe', help_text='Link color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_nav_active_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Active navigation link color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_nav_link_color',
            field=colorfield.fields.ColorField(default='#e9ecef', help_text='Navigation link color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_powered_by_color',
            field=colorfield.fields.ColorField(default='#6c757d', help_text='Powered by text color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_second_button_border_color',
            field=colorfield.fields.ColorField(default='#6c757d', help_text='Secondary button border color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_second_button_color',
            field=colorfield.fields.ColorField(default='#6c757d', help_text='Secondary button background color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_second_button_hover_color',
            field=colorfield.fields.ColorField(default='#5c636a', help_text='Secondary button hover color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_second_button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Secondary button text color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_success_color',
            field=colorfield.fields.ColorField(default='#198754', help_text='Success alert color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_tab_active_title_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Active tab title color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_tab_title_color',
            field=colorfield.fields.ColorField(default='#adb5bd', help_text='Tab title color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_text_color',
            field=colorfield.fields.ColorField(default='#e9ecef', help_text='Text color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='dark_title_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Title color for dark mode.', image_field=None, max_length=25, samples=None),
        ),
    ]
