# Generated by Django 5.0.4 on 2025-10-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0025_ndrcorecolorscheme_brand_panel_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcoresearchfield',
            name='data_field_type',
            field=models.CharField(blank=True, choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String')], default='', help_text='Type of the field in the data source. This may change the way data is queried.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ndrcoresearchfield',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Select a Type'), (1, 'String'), (2, 'Number'), (3, 'Dropdown List'), (4, 'Multi Select List'), (5, 'Boolean'), (6, 'Date'), (7, 'Date Range'), (8, 'Number Range'), (9, 'Hidden'), (10, 'Info Text'), (11, 'Boolean List'), (12, 'Float')], help_text='Type of the form field. String produces a text field, Number a number field and dictionary a dropdown.'),
        ),
    ]
