# Generated by Django 5.0.4 on 2025-10-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0026_alter_ndrcoresearchfield_data_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoresearchfield',
            name='comparison_operator',
            field=models.CharField(blank=True, choices=[('=', 'Equal to / At / Exact match'), ('>', 'Greater than / After'), ('<', 'Less than / Before'), ('>=', 'Greater than or equal / At or after'), ('<=', 'Less than or equal / At or before'), ('!=', 'Not equal to'), ('contains', 'Contains (uses regex)'), ('CHOOSE', 'Let the user decide')], default='=', help_text='Comparison operator for number, float, date, and string fields', max_length=20),
        ),
    ]
