# Generated by Django 5.0.4 on 2025-10-23 18:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0027_ndrcoresearchfield_comparison_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcorepage',
            name='template_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Text for your template page', null=True),
        ),
        migrations.AlterField(
            model_name='ndrcoreresultfield',
            name='rich_expression',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text for your expression', null=True),
        ),
        migrations.AlterField(
            model_name='ndrcorerichtexttranslation',
            name='translation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Text for your template page', null=True),
        ),
    ]
