# Generated by Django 5.0.4 on 2025-11-08 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0030_remove_ndrcoreuielement_result_card_configuration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndrcoreimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='ndrcoreimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='ndrcoreimage',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='ndrcoreimage',
            name='image_group',
        ),
        migrations.RemoveField(
            model_name='ndrcoreimage',
            name='index_in_group',
        ),
        migrations.RemoveField(
            model_name='ndrcoreimage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='ndrcoreimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ndrcoreimage',
            name='url',
        ),
        migrations.AddField(
            model_name='ndrcoreimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Alternative text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='ndrcoreimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ndrcoreimage',
            name='image_active',
            field=models.BooleanField(default=True, help_text='Set to false to hide this image from selection'),
        ),
        migrations.AlterField(
            model_name='ndrcorerichtexttranslation',
            name='table_name',
            field=models.CharField(choices=[('ndrcoresearchfield', 'Search Field Table'), ('ndrcoreresultfield', 'Result Field Table'), ('ndrcorepage', 'Page Table'), ('ndrcorevalue', 'Settings Table'), ('ndrcoresearchconfiguration', 'Search Configuration Table'), ('ndrcoreuielementitem', 'UI Element Table')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ndrcoretranslation',
            name='table_name',
            field=models.CharField(choices=[('ndrcoresearchfield', 'Search Field Table'), ('ndrcoreresultfield', 'Result Field Table'), ('ndrcorepage', 'Page Table'), ('ndrcorevalue', 'Settings Table'), ('ndrcoresearchconfiguration', 'Search Configuration Table'), ('ndrcoreuielementitem', 'UI Element Table')], max_length=100),
        ),
    ]
