# Generated by Django 5.0.4 on 2025-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0031_alter_ndrcoreimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Descriptive label for display in admin interface.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='name',
            field=models.CharField(help_text='Unique slug/identifier for calling this element via [[element|name]].', max_length=100, primary_key=True, serialize=False),
        ),
    ]
