# Generated by Django 5.0.4 on 2025-11-09 14:44

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0032_ndrcoreuielement_label_alter_ndrcoreuielement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreuielementitem',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Provider type (youtube, vimeo, switchtube, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='ndrcoreuielementitem',
            name='rich_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich formatted text content', null=True),
        ),
        migrations.AddField(
            model_name='ndrcoreuielementitem',
            name='upload_file',
            field=models.ForeignKey(blank=True, help_text='Uploaded file (audio, documents, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_element_items', to='ndr_core.ndrcoreupload'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron'), ('iframe', 'IFrame'), ('banner', 'Banner'), ('manifest_viewer', 'Manifest Viewer'), ('data_object', 'Data Object'), ('video', 'Video'), ('audio', 'Audio Player'), ('academic_about', 'Academic About Me')], help_text='Type of the element. Decides how it is rendered. ', max_length=100),
        ),
    ]
