# Generated by Django 5.0.4 on 2025-11-10 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0033_ndrcoreuielementitem_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='background_display_mode',
            field=models.CharField(choices=[('NONE', 'No Background'), ('INHERIT', 'Use Default'), ('FULL_VIEWPORT', 'Full Viewport (Hero)'), ('HEADER_ONLY', 'Header Section Only'), ('FIXED_PARALLAX', 'Fixed with Parallax')], default='INHERIT', help_text='How the background image should be displayed', max_length=20),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_backgrounds', to='ndr_core.ndrcoreimage'),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='background_position',
            field=models.CharField(default='center', help_text="CSS background-position value (e.g., 'center', 'top', 'bottom')", max_length=20),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='background_size',
            field=models.CharField(default='cover', help_text="CSS background-size value (e.g., 'cover', 'contain', 'auto')", max_length=20),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='overlay_color',
            field=models.CharField(default='#000000', help_text='Overlay color in hex format (e.g., #000000)', max_length=7),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='overlay_enabled',
            field=models.BooleanField(default=False, help_text='Enable semi-transparent overlay for better text readability'),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='overlay_opacity',
            field=models.FloatField(default=0.5, help_text='Overlay opacity (0.0 = transparent, 1.0 = opaque)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='use_default_background',
            field=models.BooleanField(default=True, help_text='Use installation default background image settings'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron'), ('iframe', 'IFrame'), ('banner', 'Banner'), ('manifest_viewer', 'Manifest Viewer'), ('data_object', 'Data Object'), ('video', 'Video'), ('audio', 'Audio Player'), ('academic_about', 'About Me')], help_text='Type of the element. Decides how it is rendered. ', max_length=100),
        ),
    ]
