# Generated by Django 5.0.4 on 2025-11-10 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0034_ndrcorepage_background_display_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='background_image_dark',
            field=models.ForeignKey(blank=True, help_text='Background image for this page in dark mode (optional, falls back to light image if not set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_backgrounds_dark', to='ndr_core.ndrcoreimage'),
        ),
    ]
