# Generated by Django 5.0.4 on 2025-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0035_ndrcorepage_background_image_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='show_footer',
            field=models.BooleanField(default=True, help_text='Show footer on this page'),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='show_navigation',
            field=models.BooleanField(default=True, help_text='Show navigation bar on this page'),
        ),
    ]
