# Generated by Django 5.0.4 on 2025-11-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0036_ndrcorepage_show_footer_ndrcorepage_show_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='center_content',
            field=models.BooleanField(default=False, help_text='Vertically center the page content (useful for hero pages)'),
        ),
    ]
