# Generated by Django 5.0.4 on 2025-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0037_ndrcorepage_center_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoresearchconfiguration',
            name='data_list_filters',
            field=models.ManyToManyField(blank=True, help_text='Search fields used as pre-filters for data list pages (using their initial values)', related_name='used_in_data_lists', to='ndr_core.ndrcoresearchfield'),
        ),
    ]
