# Generated by Django 5.0.4 on 2025-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0038_ndrcoresearchconfiguration_data_list_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcoresearchfield',
            name='data_field_type',
            field=models.CharField(blank=True, choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('boolean', 'Boolean')], default='', help_text='Type of the field in the data source. This may change the way data is queried.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron'), ('iframe', 'IFrame'), ('banner', 'Banner'), ('manifest_viewer', 'Manifest Viewer'), ('data_object', 'Data Object'), ('video', 'Video'), ('audio', 'Audio Player'), ('academic_about', 'About Me'), ('team_grid', 'Team Members Grid')], help_text='Type of the element. Decides how it is rendered. ', max_length=100),
        ),
    ]
