# Generated by Django 5.0.4 on 2026-01-20 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0039_alter_ndrcoresearchfield_data_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='tab_name',
            field=models.CharField(blank=True, help_text='Tab name to group this field under. Leave empty for no tabs.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='tab_order',
            field=models.IntegerField(default=1, help_text='Order of tabs (1 = first tab). Only applies if tab_name is set.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
