# Generated by Django 5.0.4 on 2026-01-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0040_ndrcoreresultfieldcardconfiguration_tab_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreresultfield',
            name='is_tab_container',
            field=models.BooleanField(default=False, help_text='If true, this field acts as a tab container and displays child fields as tabs'),
        ),
        migrations.AddField(
            model_name='ndrcoreresultfield',
            name='tab_children',
            field=models.JSONField(blank=True, help_text="JSON array of tab configurations: [{'tab_label': 'Info', 'result_field_id': 123, 'tab_order': 1}, ...]", null=True),
        ),
    ]
