# Generated by Django 5.0.4 on 2026-01-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0041_ndrcoreresultfield_is_tab_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='tab_name',
        ),
        migrations.RemoveField(
            model_name='ndrcoreresultfieldcardconfiguration',
            name='tab_order',
        ),
    ]
